version: "3.9"

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexell-api-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9229:9229" # For Node.js debugging
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER:-dev_user}:${MONGO_PASSWORD:-dev_password}@mongodb:27017/tasks-notes-app?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-dev_jwt_secret}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - SESSION_SECRET=${SESSION_SECRET:-dev_session_secret}
      - LOG_LEVEL=debug
      - API_BASE_URL=http://localhost:5000
    volumes:
      # Mount source code for hot reloading
      - ./:/app
      - /app/node_modules # Don't overwrite node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
      - db-network
    command: npm run dev

  mongodb:
    image: mongo:6
    container_name: nexell-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-dev_user}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-dev_password}
      - MONGO_INITDB_DATABASE=tasks-notes-app
    volumes:
      - mongodb_data_dev:/data/db
      - mongodb_config_dev:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - db-network
    command: mongod --bind_ip_all

  redis:
    image: redis:7-alpine
    container_name: nexell-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - db-network
    command: redis-server --appendonly yes

  # MongoDB web-based admin interface
  mongo-express:
    image: mongo-express:latest
    container_name: nexell-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER:-dev_user}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD:-dev_password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER:-dev_user}:${MONGO_PASSWORD:-dev_password}@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - db-network

  # Redis web-based admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nexell-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - db-network

volumes:
  mongodb_data_dev:
  mongodb_config_dev:
  redis_data_dev:
