version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/tasks-notes-app
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - CLIENT_URL=${CLIENT_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - AUTH_RATE_LIMIT_WINDOW_MS=${AUTH_RATE_LIMIT_WINDOW_MS}
      - AUTH_RATE_LIMIT_MAX_REQUESTS=${AUTH_RATE_LIMIT_MAX_REQUESTS}
      - ENABLE_SECURITY_HEADERS=${ENABLE_SECURITY_HEADERS}
      - ENABLE_CORS=${ENABLE_CORS}
      - ENABLE_RATE_LIMIT=${ENABLE_RATE_LIMIT}
      - ENABLE_COMPRESSION=${ENABLE_COMPRESSION}
      - ENABLE_LOGGING=${ENABLE_LOGGING}
      - ENABLE_HEALTH_CHECK=${ENABLE_HEALTH_CHECK}
      - NODE_OPTIONS=${NODE_OPTIONS}
    volumes:
      - app_logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true
      - no-exec:true
      - no-dev:true
      - no-setuid:true
      - no-sysctl:true
      - no-ipc:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
      - no-exec:true
      - no-dev:true
      - no-setuid:true
      - no-sysctl:true
      - no-ipc:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app_logs:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  app-network:
    driver: bridge
